index:
    path: /menu
    controller: App\Controller\DefaultController::menuAction

form_salle:
    path: /salle
    controller: App\Controller\ControllerSalle::formSalle

form_info_donnees:
    path: /donnees
    controller: App\Controller\ControllerDonnees::formDonnees 